<?php
session_start();
include("../config/db.php");
require('../fpdf/fpdf.php'); // make sure you have fpdf.php file in ../fpdf/

if(!isset($_SESSION['user_id'])){
    header("Location: login.php");
    exit;
}

$user_id = $_SESSION['user_id'];

// Fetch user details
$user_query = mysqli_query($conn, "SELECT fullname, email, phone FROM users WHERE id='$user_id'");
$user = mysqli_fetch_assoc($user_query);

// Fetch user booking history
$result = mysqli_query($conn, "
    SELECT b.*, c.car_name 
    FROM bookings b
    JOIN cars c ON b.car_id = c.id
    WHERE b.user_id='$user_id'
    ORDER BY b.id DESC
");

// Custom PDF Class
class PDF extends FPDF {
    function Header() {
        // Logo (optional)
        if(file_exists('../images/logo.png')) {
            $this->Image('../images/logo.png',10,8,20);
        }

        // Title
        $this->SetFont('Arial','B',16);
        $this->SetTextColor(33,37,41);
        $this->Cell(0,10,'Car Rental Booking History',0,1,'C');
        $this->Ln(8);

        // Line
        $this->SetDrawColor(52,58,64);
        $this->SetLineWidth(0.5);
        $this->Line(10,28,200,28);
        $this->Ln(5);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial','I',9);
        $this->SetTextColor(100,100,100);
        $this->Cell(0,10,'© '.date('Y').' Car Rental System | Page '.$this->PageNo(),0,0,'C');
    }
}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial','',12);
$pdf->SetTextColor(33,37,41);

// User Information Section
$pdf->SetFillColor(240,240,240);
$pdf->Cell(0,10,'User Details',0,1,'L',true);

$pdf->SetFont('Arial','',11);
$pdf->Cell(40,8,'Name:',0,0);
$pdf->Cell(80,8,$user['fullname'],0,1);

$pdf->Cell(40,8,'Email:',0,0);
$pdf->Cell(80,8,$user['email'],0,1);

$pdf->Cell(40,8,'Phone:',0,0);
$pdf->Cell(80,8,$user['phone'],0,1);

$pdf->Ln(5);

// Booking History Table Header
$pdf->SetFont('Arial','B',11);
$pdf->SetFillColor(52,58,64); // dark gray
$pdf->SetTextColor(255,255,255);
$pdf->Cell(10,10,'#',1,0,'C',true);
$pdf->Cell(45,10,'Car Name',1,0,'C',true);
$pdf->Cell(30,10,'Start Date',1,0,'C',true);
$pdf->Cell(30,10,'End Date',1,0,'C',true);
$pdf->Cell(25,10,'Total (₹)',1,0,'C',true);
$pdf->Cell(40,10,'Status',1,1,'C',true);

// Table Rows
$pdf->SetFont('Arial','',11);
$pdf->SetTextColor(0,0,0);
$count = 1;

if(mysqli_num_rows($result) > 0){
    while($row = mysqli_fetch_assoc($result)){
        // Alternate row colors
        $fill = ($count % 2 == 0) ? [245,245,245] : [255,255,255];
        $pdf->SetFillColor($fill[0],$fill[1],$fill[2]);
        
        // Status color text
        if($row['status'] == 'approved'){
            $status = 'Approved';
        } elseif($row['status'] == 'pending'){
            $status = 'Pending';
        } else {
            $status = 'Rejected';
        }

        $pdf->Cell(10,10,$count++,1,0,'C',true);
        $pdf->Cell(45,10,$row['car_name'],1,0,'L',true);
        $pdf->Cell(30,10,$row['start_date'],1,0,'C',true);
        $pdf->Cell(30,10,$row['end_date'],1,0,'C',true);
        $pdf->Cell(25,10,$row['total_price'],1,0,'C',true);
        $pdf->Cell(40,10,ucfirst($status),1,1,'C',true);
    }
} else {
    $pdf->Cell(0,10,'No bookings found.',1,1,'C');
}

$pdf->Ln(8);

// Footer Note
$pdf->SetFont('Arial','I',10);
$pdf->SetTextColor(100,100,100);
$pdf->MultiCell(0,8,"This document is automatically generated by Car Rental System.\nFor any queries, please contact admin.",0,'C');

// Output file
$pdf->Output('D','Booking_History.pdf');
?>
